sudo: false

language: node_js

env:
  - CXX=g++-4.8

node_js:
  - "5.0"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

script: make test-once

after_script: make test-coveralls
